package trabajolabnº4;

public class Pantalla extends javax.swing.JFrame {

    Empresa miEmpresa1 = new Empresa();
    Empresa miEmpresa2 = new Empresa();
    Empresa miEmpresa3 = new Empresa();
    Empresa miEmpresa4 = new Empresa();

    public Pantalla() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtComparaciones = new javax.swing.JTextField();
        txtIntercambios = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnSecOrd = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnSec = new javax.swing.JButton();
        btnBin = new javax.swing.JButton();
        btnIndex = new javax.swing.JButton();
        btnBloq = new javax.swing.JButton();
        txtPos = new javax.swing.JTextField();
        txtCod = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Metodos de Ordenamiento");

        jLabel2.setText("Escoja un metodo:");

        jButton1.setText("Metodo Burbuja");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Insercion Directa");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Nº Comparaciones:");

        jLabel4.setText("Nº Intercambios:");

        txtComparaciones.setEditable(false);

        txtIntercambios.setEditable(false);

        jButton3.setText("Seleccion Directa");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Metodos de Busqueda");

        btnSecOrd.setText("Secuencial Ordenado");
        btnSecOrd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSecOrdActionPerformed(evt);
            }
        });

        jLabel6.setText("Escoja un metodo:");

        btnSec.setText("Secuencial Desordenado");
        btnSec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSecActionPerformed(evt);
            }
        });

        btnBin.setText("Ordenamiento Binario");
        btnBin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBinActionPerformed(evt);
            }
        });

        btnIndex.setText("busqueda indexada");
        btnIndex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIndexActionPerformed(evt);
            }
        });

        btnBloq.setText("Secuencial por bloques");
        btnBloq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBloqActionPerformed(evt);
            }
        });

        txtPos.setEditable(false);

        txtCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodActionPerformed(evt);
            }
        });

        jLabel8.setText("Codigo:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(136, 136, 136)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton2)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtComparaciones)
                                .addComponent(txtIntercambios, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(17, 17, 17))))
                .addGap(165, 165, 165)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(177, 177, 177))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnSecOrd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnSec, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                                    .addComponent(btnBin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnBloq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnIndex, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCod, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtPos)
                                .addGap(23, 23, 23)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(txtCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addGap(87, 87, 87)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtComparaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtIntercambios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSec))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSecOrd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBin)
                        .addGap(12, 12, 12)
                        .addComponent(btnBloq)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnIndex)
                        .addGap(18, 18, 18)
                        .addComponent(txtPos, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Metodo de la burbuja
        miEmpresa1.OrdenBurbuja();
        String mensaje = "";
        for (int i = 0; i < miEmpresa1.getNumeroDeEmpleados(); i++) {
            mensaje = mensaje
                    + miEmpresa1.getCodigoDelEmpleado(i) + "---"
                    + miEmpresa1.getNombreDelEmpleado(i) + "---"
                    + miEmpresa1.getSueldoDelEmpleado(i) + "---" + "\n";
        }
        System.out.println(mensaje);
        txtComparaciones.setText(String.valueOf(miEmpresa1.getComparaciones()));
        txtIntercambios.setText(String.valueOf(miEmpresa1.getIntercambios()));

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Metodo de insercion directa.
        miEmpresa2.OrdenInsercionDirecta();
        String mensaje = "";
        for (int i = 0; i < miEmpresa2.getNumeroDeEmpleados(); i++) {
            mensaje = mensaje + miEmpresa2.getCodigoDelEmpleado(i) + "---"
                    + miEmpresa2.getNombreDelEmpleado(i) + "---"
                    + miEmpresa2.getSueldoDelEmpleado(i) + "\n";
        }
        System.out.println(mensaje);
        txtComparaciones.setText(String.valueOf(miEmpresa2.getComparaciones()));
        txtIntercambios.setText(String.valueOf(miEmpresa2.getIntercambios()));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        miEmpresa3.OrdenamientoSeleccionDirecta();
        String mensaje = "";
        for (int i = 0; i < miEmpresa3.getNumeroDeEmpleados(); i++) {
            mensaje = mensaje + miEmpresa3.getCodigoDelEmpleado(i) + "---"
                    + miEmpresa3.getNombreDelEmpleado(i) + "---"
                    + miEmpresa3.getSueldoDelEmpleado(i) + "\n";
        }
        System.out.println(mensaje);
        txtComparaciones.setText(String.valueOf(miEmpresa3.getComparaciones()));
        txtIntercambios.setText(String.valueOf(miEmpresa3.getIntercambios()));
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnSecOrdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSecOrdActionPerformed
        Integer pos = miEmpresa3.BusquedaSecuencialOrdenado(Integer.parseInt(txtCod.getText()));
        if (pos == -1) {
            txtPos.setText("no encontrado");
        } else {
            txtPos.setText(miEmpresa3.getEmpleados()[pos].toString());
        }
        String mensaje = "";
        for (int i = 0; i < miEmpresa3.getNumeroDeEmpleados(); i++) {
            mensaje = mensaje + miEmpresa3.getCodigoDelEmpleado(i) + "---"
                    + miEmpresa3.getNombreDelEmpleado(i) + "---"
                    + miEmpresa3.getSueldoDelEmpleado(i) + "\n";
        }
        System.out.println(mensaje);
        txtComparaciones.setText(String.valueOf(miEmpresa3.getComparaciones()));
    }//GEN-LAST:event_btnSecOrdActionPerformed

    private void btnSecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSecActionPerformed
        Integer pos = miEmpresa3.BusquedaSecuencialDesordenado(Integer.parseInt(txtCod.getText()));
        if (pos == -1) {
            txtPos.setText("no encontrado");
        } else {
            txtPos.setText(miEmpresa3.getEmpleados()[pos].toString());
        }
        String mensaje = "";
        for (int i = 0; i < miEmpresa3.getNumeroDeEmpleados(); i++) {
            mensaje = mensaje + miEmpresa3.getCodigoDelEmpleado(i) + "---"
                    + miEmpresa3.getNombreDelEmpleado(i) + "---"
                    + miEmpresa3.getSueldoDelEmpleado(i) + "\n";
        }
        System.out.println(mensaje);
        txtComparaciones.setText(String.valueOf(miEmpresa3.getComparaciones()));

    }//GEN-LAST:event_btnSecActionPerformed

    private void btnBinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBinActionPerformed
        Integer pos = miEmpresa3.BusquedaBinaria(Integer.parseInt(txtCod.getText()));
        if (pos == -1) {
            txtPos.setText("no encontrado");
        } else {
            txtPos.setText(miEmpresa3.getEmpleados()[pos].toString());
        }
        String mensaje = "";
        for (int i = 0; i < miEmpresa3.getNumeroDeEmpleados(); i++) {
            mensaje = mensaje + miEmpresa3.getCodigoDelEmpleado(i) + "---"
                    + miEmpresa3.getNombreDelEmpleado(i) + "---"
                    + miEmpresa3.getSueldoDelEmpleado(i) + "\n";
        }
        System.out.println(mensaje);
        txtComparaciones.setText(String.valueOf(miEmpresa3.getComparaciones()));
    }//GEN-LAST:event_btnBinActionPerformed

    private void btnIndexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIndexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIndexActionPerformed

    private void btnBloqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBloqActionPerformed
        Integer pos = miEmpresa3.BusquedaBloquesSecuencial(Integer.parseInt(txtCod.getText()));
        if (pos == -1) {
            txtPos.setText("no encontrado");
        } else {
            txtPos.setText(miEmpresa3.getEmpleados()[pos].toString());
        }
        String mensaje = "";
        for (int i = 0; i < miEmpresa3.getNumeroDeEmpleados(); i++) {
            mensaje = mensaje + miEmpresa3.getCodigoDelEmpleado(i) + "---"
                    + miEmpresa3.getNombreDelEmpleado(i) + "---"
                    + miEmpresa3.getSueldoDelEmpleado(i) + "\n";
        }
        System.out.println(mensaje);
        txtComparaciones.setText(String.valueOf(miEmpresa3.getComparaciones()));
    }//GEN-LAST:event_btnBloqActionPerformed

    private void txtCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        System.out.println("Codigo desarrollado por:");
        System.out.println("Rivera Deza Alvaro Antonio Jose         17200090");
        System.out.println("Kochi Nagamine Jimmy                    17200091");
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantalla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBin;
    private javax.swing.JButton btnBloq;
    private javax.swing.JButton btnIndex;
    private javax.swing.JButton btnSec;
    private javax.swing.JButton btnSecOrd;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtCod;
    private javax.swing.JTextField txtComparaciones;
    private javax.swing.JTextField txtIntercambios;
    private javax.swing.JTextField txtPos;
    // End of variables declaration//GEN-END:variables
}
